### ISSUE TITLE
No Tray Icon / Window Gone (Ubuntu + Gnome)

### ISSUE THREAD

**Issue by crash83k** [sidneys/pb-for-desktop#79]
## 🤷🏽‍♂️ Current Behaviour

When starting PB, I don't have any tray icon. I set up PB and it seemed to be working correctly. But noticed the tray wasn't there at all.

I closed PB expecting to reopen it and see if the tray icon appeared since I've set up the app. It did not, nor did the window itself. PB was apparently running in the background (4 processes running for it).

I killed those processes, expecting that now I can open PB again and the window would appear. It does not. (Did it save the state of the window being closed?)

## 🎯 Expected Behaviour

A tray icon should appear when the app opens. And the app should open when it's started (?) maybe as an option.

## 👟 Steps to Reproduce (S2R)

 1. Open PB in Ubuntu+Gnome
 2. Close window.
 3. Find PB process and kill them.
 4. Reopen PB.

## 🏡 Environmental Context

**App Version**
v6.8.1
**Installation Type** 
amd64.deb
**Operating System**
Ubuntu 17.10 (64bit)
Gnome 3.26

**Comment by crash83k** [comment]
BTW, I got the window to show up again by changing `"windowVisible":false` to `"windowVisible":true` in the `.config/PB for Desktop/pb-for-desktop.json` file.

**Comment by sidneys** [comment]
@crash83k 

Thanks for your report! This is a longstanding upstream issue (https://github.com/electron/electron/issues/10427), a fix has been slated for inclusion in the upcoming release.

Cheers,
S

**Comment by sidneys** [comment]
@crash83k 

This issue was addressed in [v6.9.0](https://github.com/sidneys/pb-for-desktop/releases).

Cheers,
S

**Comment by crash83k** [comment]
Gave it a try. Still no tray icon. :( To be fair, I think the entire Ubuntu 17.10 app indicator system is fubar.

At this point, sometimes the slack icon shows up, and most of the time it doesn't. Worse, the vast majority of icons just don't work at all. I don't use Top Icons (or Top Icons Plus). I'm just using the default stock indicator.

I'm thinking about ditching Gnome at this point, though. Since they don't think apps should have a status icon (which is just ridiculous to me), I'm probably going to try Pantheon.

Hopefully you guys get this fixed. I wish I had the time to help you guys out on this, though. It's a neat project, and I hate having to run Chrome to use PB. Firefox's PB extension is not remotely there yet.

**Comment by hoax92** [comment]
the icon's not visible in KDE after updating to 6.9.0

**Comment by AyserJamshidi** [comment]
Issue persists on 6.9.1 for Pop!_OS/Gnome, also tried Plasma KDE, no tray icon still.

**Comment by ghost** [comment]
Reporting that the issue persists here too using 6.9.1 with KDE Plasma 5.12.4.

**Comment by divadsn** [comment]
No issue on Gnome 3.28 running Arch Linux.

**Comment by sonvirgo** [comment]
Any thing new? 
Version 7.0
No top-bar/dash/cairo Ubtuntu Gnome 17.10
